services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - ENVIRONMENT=development
      - SECRET_KEY=dev-secret-key-change-in-production
      - GCP_PROJECT_ID=lexiconnect-free
    volumes:
      - ./backend:/app
    depends_on:
      - neo4j
    restart: unless-stopped
    networks:
      - lexiconnect-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - lexiconnect-network

  neo4j:
    image: neo4j:5.14-community
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    ports:
      - "7474:7474" # Browser interface
      - "7687:7687" # Bolt protocol
    restart: unless-stopped
    networks:
      - lexiconnect-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  lexiconnect-network:
    driver: bridge
